package net.tclproject.biomeidextender;

import net.minecraft.util.EnumChatFormatting;

import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;
import cpw.mods.fml.common.gameevent.TickEvent;

import net.minecraftforge.common.MinecraftForge;
import net.tclproject.biomeidextender.utils.LogHelper;
import code.elix_x.coremods.antiidconflict.managers.*;

import java.util.Collections;
import java.util.Random;

@Mod(modid = ModProperties.MODID, name = ModProperties.NAME, version = ModProperties.VERSION)
public class BiomeIDExtender {
   private static int tickCounter = 0; // Creates the tick counter, in case the debug mode is enabled.

   @EventHandler
   public void preInit(FMLPreInitializationEvent event) {
      MinecraftForge.EVENT_BUS.register(this);
      FMLCommonHandler.instance().bus().register(this);

      makeFancyModInfo(event);
      Config.createConfigFile();

      if (Loader.isModLoaded("antiidconflict")) BiomesManager.conflicts = new BiomesManager.ConflictingBiomes[65536];
   }


   @EventHandler
   public void init(FMLInitializationEvent event) {
   }


   @EventHandler
   public void postInit(FMLPostInitializationEvent event) {
   }


   @SubscribeEvent
   public void handlePlayerTick(TickEvent.PlayerTickEvent event) {
      if (Config.debugMode) {
         if (tickCounter >= 80) {
            LogHelper.info(LogHelper.format("[DEBUG MODE] Biome: %s, Biome ID: %s, Is server?: %s", event.player.worldObj.getBiomeGenForCoords((int) event.player.posX, (int) event.player.posZ).biomeName, event.player.worldObj.getBiomeGenForCoords((int) event.player.posX, (int) event.player.posZ).biomeID, !event.player.worldObj.isRemote));
            if (tickCounter >= 81) tickCounter = 0;
         }

         tickCounter += 1;
      }
   }


   public void makeFancyModInfo(FMLPreInitializationEvent event) {
      // The following will overwrite the mcmod.info file so the info page looks good.
      // Adapted from Jabelar's Magic Beans and AstroTibs's OptionsEnforcer.

      LogHelper.info("Generating the mod info page...");

      // This will stop Forge from complaining about missing mcmod.info (just in case i forget it).
      event.getModMetadata().autogenerated = false;

      event.getModMetadata().name = ModProperties.COLORED_NAME; // Mod name
      event.getModMetadata().version = ModProperties.COLORED_VERSION; // Mod version
      event.getModMetadata().credits = ModProperties.CREDITS; // Mod credits

      // Author list
      event.getModMetadata().authorList.clear();
      Collections.addAll(event.getModMetadata().authorList, ModProperties.AUTHORS);

      event.getModMetadata().url = ModProperties.COLORED_URL; // Mod URL

      // Mod description
      event.getModMetadata().description = ModProperties.DESCRIPTION + "\n\n" + EnumChatFormatting.DARK_GRAY + EnumChatFormatting.ITALIC +
              ModProperties.SPLASH_OF_THE_DAY[(new Random()).nextInt(ModProperties.SPLASH_OF_THE_DAY.length)];

      if (ModProperties.LOGO != null) event.getModMetadata().logoFile = ModProperties.LOGO; // Mod logo
   }
}
